doc-warnings: false 
pylint: 
    disable:                        # ignore the following two non-error "errors"
        - redefined-builtin  
        - pointless-string-statement 
python-targets: 
    - 2
    - 3 
